"""Code generation: emit standalone Python wrapper files for a CLI.

Usage (from CLI): `cli-to-py git -o git_wrapper.py`

The generated file is a standalone Python module that imports only from the
stdlib. It embeds a tiny `_run` helper and exports a snake_cased function per
subcommand, plus a `run` function for the root command. Drop into any project,
zero dependencies.

Also generates a .pyi stub for type-checking / IDE autocomplete.
"""

from __future__ import annotations

import json as _json
import re


from .case import kebab_to_snake
from .constants import SHORT_FLAG_MAX_LENGTH
from .schema import CliSchema, ParsedFlag, ParsedSubcommand


def _to_identifier(name: str) -> str:
    """Convert arbitrary text to a valid Python identifier."""
    ident = re.sub(r"[^a-zA-Z0-9_]+", "_", name).strip("_")
    if not ident:
        ident = "_"
    if ident[0].isdigit():
        ident = "_" + ident
    # Avoid Python keywords
    import keyword
    if keyword.iskeyword(ident):
        ident = ident + "_"
    return ident


def _flag_type_hint(flag: ParsedFlag) -> str:
    if not flag.takes_value:
        return "bool"
    if flag.choices:
        choices_str = ", ".join(f'"{c}"' for c in flag.choices)
        return f"Literal[{choices_str}]"
    return "str"


def _flag_comment(flag: ParsedFlag) -> str:
    names: list[str] = []
    if flag.short_name:
        names.append(flag.short_name)
    names.append(f"--{flag.long_name}")
    joined = ", ".join(names)
    if flag.takes_value and flag.value_name:
        joined += f" <{flag.value_name}>"
    desc = f" — {flag.description}" if flag.description else ""
    return f"    # {joined}{desc}"


def _equals_keys(flags: list[ParsedFlag] | None) -> set[str]:
    if not flags:
        return set()
    keys: set[str] = set()
    for flag in flags:
        if not flag.uses_equals:
            continue
        keys.add(kebab_to_snake(flag.long_name))
        if flag.short_name:
            keys.add(flag.short_name.lstrip("-"))
            keys.add(flag.short_name)
    return keys


def _set_literal(values: set[str]) -> str:
    if not values:
        return "set()"
    return "{" + ", ".join(repr(v) for v in sorted(values)) + "}"


def _subcommand_function_names(
    subcommands: list[ParsedSubcommand],
) -> list[tuple[ParsedSubcommand, str]]:
    used = {"run", "run_async"}
    result: list[tuple[ParsedSubcommand, str]] = []
    for sub in subcommands:
        base = _to_identifier(sub.name)
        ident = base
        suffix = 2
        while ident in used or f"{ident}_async" in used:
            ident = f"{base}_{suffix}"
            suffix += 1
        used.add(ident)
        used.add(f"{ident}_async")
        result.append((sub, ident))
    return result


_RUNTIME_TEMPLATE = '''\
# Auto-generated by cli-to-py. Do not edit manually.
# Binary: {binary!r}

from __future__ import annotations

import asyncio
import json as _json
import subprocess
from dataclasses import dataclass
from typing import Any, Sequence


BINARY: str = {binary!r}


@dataclass
class CommandResult:
    stdout: str
    stderr: str
    exit_code: int

    def ok(self) -> bool:
        return self.exit_code == 0


def _snake_to_kebab(name: str) -> str:
    return name.replace("_", "-")


def _to_args(options: dict, equals_flags: set[str] | None = None) -> list[str]:
    equals_flags = equals_flags or set()
    flag_args: list[str] = []
    positional_args: list[str] = []
    for key, value in options.items():
        if key == "_":
            if value is None:
                continue
            items = value if isinstance(value, (list, tuple)) else [value]
            positional_args.extend(str(item) for item in items)
            continue
        if key.startswith("-"):
            flag_name = key
        elif len(key) <= {short_max}:
            flag_name = f"-{{key}}"
        else:
            flag_name = f"--{{_snake_to_kebab(key)}}"
        use_equals = key in equals_flags
        if isinstance(value, bool):
            if value:
                flag_args.append(flag_name)
        elif isinstance(value, (list, tuple)):
            for item in value:
                if use_equals:
                    flag_args.append(f"{{flag_name}}={{item}}")
                else:
                    flag_args.extend([flag_name, str(item)])
        elif value is not None:
            if use_equals:
                flag_args.append(f"{{flag_name}}={{value}}")
            else:
                flag_args.extend([flag_name, str(value)])
    return flag_args + positional_args


def _run_sync(
    subcommand: Sequence[str],
    options: dict,
    equals_flags: set[str] | None = None,
) -> CommandResult:
    completed = subprocess.run(
        [BINARY, *subcommand, *_to_args(options, equals_flags)],
        capture_output=True,
        text=True,
        check=False,
    )
    return CommandResult(
        stdout=completed.stdout or "",
        stderr=completed.stderr or "",
        exit_code=completed.returncode if completed.returncode is not None else 1,
    )


async def _run_async(
    subcommand: Sequence[str],
    options: dict,
    equals_flags: set[str] | None = None,
) -> CommandResult:
    proc = await asyncio.create_subprocess_exec(
        BINARY, *subcommand, *_to_args(options, equals_flags),
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()
    return CommandResult(
        stdout=stdout.decode("utf-8", errors="replace"),
        stderr=stderr.decode("utf-8", errors="replace"),
        exit_code=proc.returncode if proc.returncode is not None else 1,
    )
'''


def generate_wrapper(schema: CliSchema) -> str:
    """Emit a standalone Python wrapper for the given schema."""
    binary = schema.binary_name
    lines: list[str] = [_RUNTIME_TEMPLATE.format(binary=binary, short_max=SHORT_FLAG_MAX_LENGTH)]

    for sub, ident in _subcommand_function_names(schema.command.subcommands):
        sub_repr = _json.dumps([sub.name])
        equals_repr = _set_literal(_equals_keys(sub.flags))
        desc = sub.description.replace('"""', '\\"\\"\\"') if sub.description else ""

        lines.append("")
        lines.append("")
        lines.append(f"def {ident}(**options: Any) -> CommandResult:")
        if desc:
            lines.append(f'    """{binary} {sub.name} — {desc}"""')
        else:
            lines.append(f'    """{binary} {sub.name}"""')
        if sub.flags:
            for flag in sub.flags:
                lines.append(_flag_comment(flag))
        lines.append(f"    return _run_sync({sub_repr}, options, {equals_repr})")

        lines.append("")
        lines.append("")
        lines.append(f"async def {ident}_async(**options: Any) -> CommandResult:")
        lines.append(f'    """{binary} {sub.name} — async"""')
        lines.append(f"    return await _run_async({sub_repr}, options, {equals_repr})")

    lines.append("")
    lines.append("")
    lines.append("def run(**options: Any) -> CommandResult:")
    lines.append(f'    """Run {binary} directly (root command)."""')
    lines.append(f"    return _run_sync([], options, {_set_literal(_equals_keys(schema.command.flags))})")
    lines.append("")
    lines.append("")
    lines.append("async def run_async(**options: Any) -> CommandResult:")
    lines.append(f'    """Run {binary} directly — async."""')
    lines.append(f"    return await _run_async([], options, {_set_literal(_equals_keys(schema.command.flags))})")
    lines.append("")

    return "\n".join(lines)


def generate_stub(schema: CliSchema) -> str:
    """Emit a .pyi type stub with per-subcommand kwarg signatures."""
    binary = schema.binary_name
    has_literal = any(
        sub.flags and any(f.choices for f in sub.flags)
        for sub in schema.command.subcommands
    ) or any(f.choices for f in schema.command.flags)

    lines: list[str] = [
        "# Auto-generated type stub by cli-to-py. Do not edit manually.",
        "",
        "from dataclasses import dataclass",
    ]
    if has_literal:
        lines.append("from typing import Any, Literal, Sequence")
    else:
        lines.append("from typing import Any, Sequence")
    lines.extend([
        "",
        "BINARY: str",
        "",
        "@dataclass",
        "class CommandResult:",
        "    stdout: str",
        "    stderr: str",
        "    exit_code: int",
        "    def ok(self) -> bool: ...",
        "",
    ])

    def emit_func(name: str, flags: list[ParsedFlag] | None, positional_name: str = "_") -> list[str]:
        sigs: list[str] = []
        if flags:
            for flag in flags:
                snake = kebab_to_snake(flag.long_name)
                ident = _to_identifier(snake)
                hint = _flag_type_hint(flag)
                sigs.append(f"    {ident}: {hint} = ...,")
        out: list[str] = []
        out.append(f"def {_to_identifier(name)}(")
        out.append("    *,")
        out.extend(sigs)
        out.append(f"    _: str | Sequence[str] | None = ...,")
        out.append(") -> CommandResult: ...")
        out.append("")
        return out

    for sub, ident in _subcommand_function_names(schema.command.subcommands):
        lines.extend(emit_func(ident, sub.flags))
        lines.append(f"async def {ident}_async(**options: Any) -> CommandResult: ...")
        lines.append("")

    lines.extend(emit_func("run", schema.command.flags))
    lines.append("async def run_async(**options: Any) -> CommandResult: ...")
    lines.append("")
    return "\n".join(lines)


def generate_json(schema: CliSchema) -> str:
    """Dump the schema as JSON."""
    import dataclasses
    return _json.dumps(
        {"binary_name": schema.binary_name, "command": dataclasses.asdict(schema.command)},
        indent=2,
    )
